# permissions for end users to view conjurconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conjurconfig-viewer-role
rules:
- apiGroups:
  - conjur.cyberark.com
  resources:
  - conjurconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - conjur.cyberark.com
  resources:
  - conjurconfigs/status
  verbs:
  - get
