# permissions for end users to edit conjurconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conjurconfig-editor-role
rules:
- apiGroups:
  - conjur.cyberark.com
  resources:
  - conjurconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - conjur.cyberark.com
  resources:
  - conjurconfigs/status
  verbs:
  - get
